// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1G-aPtWtPEtRDHcgYkWIecA0qYHJ1W_U',
    appId: '1:179998859052:web:1e34f1f220767cf885d689',
    messagingSenderId: '179998859052',
    projectId: 'moneytrack-9de53',
    authDomain: 'moneytrack-9de53.firebaseapp.com',
    storageBucket: 'moneytrack-9de53.appspot.com',
    measurementId: 'G-0T1G4HWZCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnmoRoVTLJ3vMx4iCKfyeeIlfQ_Bfk-mg',
    appId: '1:179998859052:android:82ee90db91d308a185d689',
    messagingSenderId: '179998859052',
    projectId: 'moneytrack-9de53',
    storageBucket: 'moneytrack-9de53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlbGuNwF93wHTsc3BqljEVwHV4M32PE2c',
    appId: '1:179998859052:ios:b942744b5b784e0185d689',
    messagingSenderId: '179998859052',
    projectId: 'moneytrack-9de53',
    storageBucket: 'moneytrack-9de53.appspot.com',
    iosBundleId: 'com.example.moneytracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlbGuNwF93wHTsc3BqljEVwHV4M32PE2c',
    appId: '1:179998859052:ios:b942744b5b784e0185d689',
    messagingSenderId: '179998859052',
    projectId: 'moneytrack-9de53',
    storageBucket: 'moneytrack-9de53.appspot.com',
    iosBundleId: 'com.example.moneytracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1G-aPtWtPEtRDHcgYkWIecA0qYHJ1W_U',
    appId: '1:179998859052:web:619f53f8214f525685d689',
    messagingSenderId: '179998859052',
    projectId: 'moneytrack-9de53',
    authDomain: 'moneytrack-9de53.firebaseapp.com',
    storageBucket: 'moneytrack-9de53.appspot.com',
    measurementId: 'G-GZKYW50G3V',
  );
}
